spring:
    datasource:
        url: jdbc:h2:mem:mydb
        username: sa
        password:
        driverClassName: org.h2.Driver

    liquibase:
        change-log: classpath:db/changelog/https/liquibase-changelog.xml
